//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.sys
{
    /// <summary>
    /// 语言枚举
    /// </summary>
    public enum Language
    {
        /// <summary>
        /// 未知
        /// </summary>
        Unknown = 42,
        /// <summary>
        /// 英语
        /// </summary>
        English = 10,
        /// <summary>
        /// 简体中文
        /// </summary>
        ChineseSimplified = 40,
    }
}
