//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Game
{

public sealed partial class TbLocalization
{
    private readonly Dictionary<string, Game.Localization> _dataMap;
    private readonly List<Game.Localization> _dataList;
    
    public TbLocalization(JSONNode _json)
    {
        _dataMap = new Dictionary<string, Game.Localization>();
        _dataList = new List<Game.Localization>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Game.Localization.DeserializeLocalization(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
        PostInit();
    }

    public Dictionary<string, Game.Localization> DataMap => _dataMap;
    public List<Game.Localization> DataList => _dataList;

    public Game.Localization GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Game.Localization Get(string key) => _dataMap[key];
    public Game.Localization this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}