//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Game
{

public sealed partial class TbUIPath
{

     private readonly Game.UIPath _data;

    public TbUIPath(JSONNode _json)
    {
        if(!_json.IsArray)
        {
            throw new SerializationException();
        }
        if (_json.Count != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = Game.UIPath.DeserializeUIPath(_json[0]);
        PostInit();
    }

    /// <summary>
    /// Canvas
    /// </summary>
     public string Canvas => _data.Canvas;
    /// <summary>
    /// 更新信息面板
    /// </summary>
     public string UpdateInfoPanel => _data.UpdateInfoPanel;
    /// <summary>
    /// 登陆面板
    /// </summary>
     public string LoginPanel => _data.LoginPanel;
    /// <summary>
    /// Dialog
    /// </summary>
     public string DialogPanel => _data.DialogPanel;
    /// <summary>
    /// 左下角loading图标
    /// </summary>
     public string LoadingIcon => _data.LoadingIcon;

    public void Resolve(Dictionary<string, object> _tables)
    {
        _data.Resolve(_tables);
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        _data.TranslateText(translator);
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}